added protocol 407 for MCPE 1.16
jasonwynn10/EasyCommandAutofill pull request #6
Opened 2020-06-26 20:29 UTC by suerion

2020-06-26 20:36 UTC, jasonwynn10 commented
Tested?

2020-06-26 21:27 UTC, suerion commented
> 
> 
> Tested?

Yes, no problems, with windows 10,

xbox looks a little bit strange, but it work

2020-06-26 22:24 UTC, jasonw4331 requested changes

2020-06-26 22:24 UTC, jasonwynn10 commented on plugin.yml
> +author: "jasonwynn10"
new line at end of file needs removed

2020-06-26 22:24 UTC, jasonwynn10 commented on plugin.yml
> + #Added Protocol 407 for MCPE 1.16
please remove the comment for the protocol

2020-06-26 22:33 UTC, suerion commented
should be resolved

2020-06-26 22:38 UTC, jasonwynn10 commented
There's still a new line at the end of the file

2020-06-26 22:40 UTC, suerion commented
i deleted it allways, but it add it after commit the pull request, weired

2020-06-26 22:42 UTC, HimmelKreis4865 commented
I had actually the same problem as you, maybe ur using CRLF instead of LF line separator.

2020-06-27 21:56 UTC, jasonwynn10 commented
seriously dude, fix your line endings...

2020-06-27 23:22 UTC, suerion commented
i will close this pull request, i hope you could say me, whats the problem, i work with eclips and the lf line seperator, but it does not chenge anything...

2020-06-27 23:22 UTC, closed without merging